### ISSUE TITLE
delete-rule in Firewalls not working

### ISSUE THREAD

**Issue by nikolafilipovic** [hetznercloud/cli#320] opened 2021-04-30 19:31 UTC
Hi all, 

For some reason, I'm unable to delete a rule through CLI for a specified firewall.

Attaching a screenshot that shows the issue I'm running into:
![image](https://user-images.githubusercontent.com/2302584/116744546-bba4f400-a9fa-11eb-92d1-97ef82562eb2.png)

For reference, here are the commands I used.

Creating the firewall rule:
`hcloud firewall add-rule {{FIREWALL_NAME}} --direction in --protocol tcp --port 22 --source-ips @("1.1.1.1/32")`

Deleting the firewall rule:
`hcloud firewall delete-rule {{FIREWALL_NAME}} --direction in --protocol tcp --port 22 --source-ips @("1.1.1.1/32")`

Am I missing something or did I just come across a bug?

Thanks!

**Comment by TomSDEVSN** [comment] 2021-05-13 15:02
I can confirm it is a bug in the validation part.

The existing firewall rules have an empty `DestinationIPs` slice. For comparison, the CLI creates a temporary firewall object which has a nil-slice for `DestinationIPs`. The result is a correct behaviour from `result.DeepEqual` because the slices do not match.

I have opened a PR with a fix (see !324).

**Comment by LKaemmerling** [comment] 2021-05-17 13:22
Hey @nikolafilipovic,

thank you for the report. @TomSDEVSN fixed it in #324 and the fix will be part of the next release. Therefore I will close the issue.

Thank you!

**Closed by LKaemmerling** 2021-05-17 13:22 UTC
