### ISSUE TITLE
Snapshot failing with message that all is ok.

### ISSUE THREAD

**Issue by blyb2592** [hetznercloud/cli#101] opened 2018-03-23 15:51 UTC
When running several snapshot in a project at one time they tend to fail. 
The worst thing is that the tool gives a message:
>Image [image number] created from server [server name]

For example when issuing a command:

` hcloud server create-image --type snapshot --description "${HOSTNAME}_$(date +%Y%m%d)_DAILY1" "${SERVER_ID}" `

I get a respone:

> Image 62316 created from server SF1

And after that after issuing:

`hcloud image describe 62316 `

I get a respone:

> hcloud: image not found: 62316

Please work on having a message indicating that the snapshot was not executed.

**Comment by thcyron** [comment] 2018-04-03 08:55
The problem is that the CLI immediately prints the image ID and does not wait for the corresponding action to be finished. In your case the action failed and the CLI should report it.

**Comment by thcyron** [comment] 2018-04-05 05:55
Actually the problem is this line:

https://github.com/hetznercloud/cli/blob/2e73eed2d2e9443581be6aa7385d5c41d8362e0b/util.go#L59

It should be `errCh <- err`. Will be fixed in #104.

Thanks for reporting and sorry for the trouble.

**Closed by thcyron** 2018-04-05 05:55 UTC
Labels: bug
